In [3]:
import pandas as pd

In [4]:
data=pd.read_csv("all_kindle_review.csv")

In [5]:
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [6]:
data.shape

(12000, 11)

In [7]:
data=data[["rating","reviewText"]]

In [8]:
data

rating                                         reviewText
0           3  Jace Rankin may be short, but he's nothing to ...
1           5  Great short read.  I didn't want to put it dow...
2           3  I'll start by saying this is the first of four...
3           3  Aggie is Angela Lansbury who carries pocketboo...
4           4  I did not expect this type of book to be in li...
...       ...                                                ...
11995       4  Valentine cupid is a vampire- Jena and Ian ano...
11996       5  I have read all seven books in this series. Ap...
11997       3  This book really just wasn't my cuppa.  The si...
11998       1  tried to use it to charge my kindle, it didn't...
11999       3  Taking Instruction is a look into the often hi...

[12000 rows x 2 columns]

In [9]:
data.isnull().sum()

rating        0
reviewText    0
dtype: int64

In [10]:
##data donot contain any missing value
##let look the unique values in rating
data["rating"].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [11]:
data["rating"].value_counts()

5    3000
4    3000
3    2000
2    2000
1    2000
Name: rating, dtype: int64

In [12]:
##preprocessing and cleaning
## here im considering rating greater than 3 as positive review and less than as negative review
data["rating"]=data["rating"].apply(lambda x : 0 if x<3 else 1)

In [13]:
data

rating                                         reviewText
0           1  Jace Rankin may be short, but he's nothing to ...
1           1  Great short read.  I didn't want to put it dow...
2           1  I'll start by saying this is the first of four...
3           1  Aggie is Angela Lansbury who carries pocketboo...
4           1  I did not expect this type of book to be in li...
...       ...                                                ...
11995       1  Valentine cupid is a vampire- Jena and Ian ano...
11996       1  I have read all seven books in this series. Ap...
11997       1  This book really just wasn't my cuppa.  The si...
11998       0  tried to use it to charge my kindle, it didn't...
11999       1  Taking Instruction is a look into the often hi...

[12000 rows x 2 columns]

In [14]:
##lower the text
data["reviewText"] = data["reviewText"].str.lower()

In [15]:
import re
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\apasi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [16]:
from bs4 import BeautifulSoup

In [17]:
# Removing special characters
data["reviewText"] = data["reviewText"].apply(lambda x: re.sub(r'[^a-zA-Z0-9 ]+', '', str(x)))

# Removing stopwords
stop_words = set(stopwords.words("english"))  # Load the stopwords list
data["reviewText"] = data["reviewText"].apply(lambda x: " ".join([word for word in str(x).split() if word.lower() not in stop_words]))

# Removing URLs
data["reviewText"] = data["reviewText"].apply(lambda x: re.sub(r'https?://\S+|www\.\S+', '', str(x)))

# Removing HTML tags
data["reviewText"] = data["reviewText"].apply(lambda x: BeautifulSoup(str(x), 'lxml').get_text())

# Removing additional spaces
data["reviewText"] = data["reviewText"].apply(lambda x: " ".join(str(x).split()))


In [18]:
data

rating                                         reviewText
0           1  jace rankin may short hes nothing mess man hau...
1           1  great short read didnt want put read one sitti...
2           1  ill start saying first four books wasnt expect...
3           1  aggie angela lansbury carries pocketbooks inst...
4           1  expect type book library pleased find price right
...       ...                                                ...
11995       1  valentine cupid vampire jena ian another vampi...
11996       1  read seven books series apocalypticadventure o...
11997       1  book really wasnt cuppa situation man capturin...
11998       0  tried use charge kindle didnt even register ch...
11999       1  taking instruction look often hidden world sex...

[12000 rows x 2 columns]

In [19]:
## using lemmatizer
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()

In [20]:
def lemmatize_data(text):
    return " ".join([lemma.lemmatize(word) for word in text.split()])

In [21]:
data["reviewText"]=data["reviewText"].apply(lambda x : lemmatize_data(x))

In [22]:
data

rating                                         reviewText
0           1  jace rankin may short he nothing mess man haul...
1           1  great short read didnt want put read one sitti...
2           1  ill start saying first four book wasnt expecti...
3           1  aggie angela lansbury carry pocketbook instead...
4           1  expect type book library pleased find price right
...       ...                                                ...
11995       1  valentine cupid vampire jena ian another vampi...
11996       1  read seven book series apocalypticadventure on...
11997       1  book really wasnt cuppa situation man capturin...
11998       0  tried use charge kindle didnt even register ch...
11999       1  taking instruction look often hidden world sex...

[12000 rows x 2 columns]

In [23]:
y=data["rating"]
X=data["reviewText"]

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()

In [26]:
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()

In [28]:
X_train_tf = tf.fit_transform(X_train).toarray()
X_test_tf = tf.transform(X_test).toarray()

In [29]:
from sklearn.naive_bayes import GaussianNB

In [30]:
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tf=GaussianNB().fit(X_train_tf,y_train)

In [31]:
y_pred_bow = nb_model_bow.predict(X_test_bow)
y_pred_tf = nb_model_tf.predict(X_test_tf)

In [36]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [37]:
confusion_matrix(y_pred_bow,y_test)

array([[ 641,  861],
       [ 383, 1115]], dtype=int64)

In [34]:
##accuracy of bag of word
accuracy_score(y_pred_bow,y_test)

0.5853333333333334

In [38]:
confusion_matrix(y_pred_tf,y_test)

array([[ 620,  837],
       [ 404, 1139]], dtype=int64)

In [35]:
##accuracy of tf-idf
accuracy_score(y_pred_tf,y_test)

0.5863333333333334

In [39]:
print(classification_report(y_pred_bow,y_test))
print(classification_report(y_pred_tf,y_test))

              precision    recall  f1-score   support

           0       0.63      0.43      0.51      1502
           1       0.56      0.74      0.64      1498

    accuracy                           0.59      3000
   macro avg       0.60      0.59      0.57      3000
weighted avg       0.60      0.59      0.57      3000

              precision    recall  f1-score   support

           0       0.61      0.43      0.50      1457
           1       0.58      0.74      0.65      1543

    accuracy                           0.59      3000
   macro avg       0.59      0.58      0.57      3000
weighted avg       0.59      0.59      0.58      3000

